### ISSUE TITLE
sphinx entry point fails due to missing arguments

### ISSUE THREAD

**Issue by heat-wave** [stef/pwdsphinx#11]
**System**:
Arch Linux x86_64 Linux 5.9.14-arch1-1

**Steps to reproduce**:
- install pwdsphinx from pip3
- run sphinx with any arguments

**Expected result**:
Correct input runs the specified operation, incorrect input shows help prompt
**Actual result**:
Error: `main() missing 1 required positional argument: 'params'`

/usr/local/bin/sphinx contains the following code:

> if __name__ == '__main__':
>     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
>     sys.exit(load_entry_point('pwdsphinx==0.5', 'console_scripts', 'sphinx')())

Passing `sys.argv` to the entry point is enough to make things work -- could this be some unexpected behavior of `easy_install`?

This seems to be an installation issue not related to the code, but I thought it's worth pointing out.

**Comment by stef** [comment]
thanks for this report. i'll have a look.

**Comment by stef** [comment]
hope it works now for you! new release will be coming when i have the websphinx stuff sorted out. i hope within the next 1-2 days.
