### ISSUE TITLE
oracle server config improvement suggestions

### ISSUE THREAD

**Issue by rolfschr** [stef/pwdsphinx#13]
Hi,

I have some remarks on the sphinx.cfg ``[server]`` section.

The [current example server config](https://github.com/stef/pwdsphinx/blob/55e0398e0957ecd075b7af51e5d2dcca28fc2110/sphinx.cfg_sample#L12) specifies a 'keydir'. Is this needed? I could not find any reference to that config option in the code base.

The ``datadir`` can currently contain the tilde character (``~``) because it gets [expanded](https://github.com/stef/pwdsphinx/blob/master/pwdsphinx/oracle.py#L16). Would that be possible to do this for the ssl key/cert files, too? This would allow easier testing.

Best,
Rolf

**Comment by stef** [comment]
hey Rolf, you're right, keydir is obsolete, i removed it; https://github.com/stef/pwdsphinx/commit/41124faca9a7dc7cf2c2a48381bd9dd3fbf736ad thanks for pointing that out!

tilde expansion will be added asap.i'll update here when i do - note also in zphinx.

**Comment by stef** [comment]
hey Rolf,
pwdsphinx now tildexpands ssl_(key|cert): https://github.com/stef/pwdsphinx/commit/c29b9a259c21122dadb4e608d9d8aac8d8bc8a85
and also zphinx does so https://github.com/stef/zphinx-zerver/commit/5e4b7af350bed33ae52de17e11b2d65dc4edc691

if you agree, please close this issue. thanks for suggesting this improvement!

**Comment by rolfschr** [comment]
Perfect, thanks!
