### ISSUE TITLE
Questions about sphinxlib

### ISSUE THREAD

**Issue by skurzhanskyi** [stef/pwdsphinx#3]
I trying to build `pwdsphinx`, but there always `ValueError` during `challenge` and `finish`
So, I would like to ask:
1. Why do you need to wrap `sphinx_challenge` in `__check` if `sphinx_challenge` is void function?
2. In my case, there are always `ValueError` during `challenge` and `finish`, while with `respond` everything is ok. Maybe you have some suggestions?

Thanks a lot

**Comment by stef** [comment]
hey, re: 1. you are correct this check is not needed and it seems it is historical. i removed it in 7f09347.
re: 2. is interesting does the test in libsphinx/src/tests/sphinx run correctly and return the value `0e7c3b3d1fb91a6ac4fede91b5a175da03c841259a2066928deed1810bdab32e`? is the `ValueError` after finish blank or does it contain some hint like "truncated point" or "truncated secret"?

**Comment by skurzhanskyi** [comment]
Trying to solve proble related with running on OSX libsphinx/src/tests/sphinx.
It has `ValueError` blank. The one that is in `__check`.

**Comment by skurzhanskyi** [comment]
Yes, I get the value you metioned.

**Comment by stef** [comment]
can you post the code that you use for calling the pwdsphinx wrapper please? and also which python version are you using?

**Comment by skurzhanskyi** [comment]
python 3.7
`echo 'my master password' | python3 ./sphinx.py create username https://example.com ulsd 0`
just after `python3 ./oracle.py`

**Comment by skurzhanskyi** [comment]
I have smth like:
```
echo 'my master password' | python3 ./sphinx.py create username https://example.com ulsd 0
Fatal error: protocol.data_received() call failed.
protocol: <__main__.SphinxClientProtocol object at 0x10e5af748>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "./sphinx.py", line 57, in data_received
    rwd=sphinxlib.finish(self.b, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pwdsphinx/sphinxlib.py", line 66, in finish
    __check(sphinxlib.sphinx_finish(bfac, resp, rwd))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pwdsphinx/sphinxlib.py", line 35, in __check
    raise ValueError
ValueError
```

**Comment by skurzhanskyi** [comment]
at the same time there are ni problems with `respond` at `oracle.py`

**Comment by stef** [comment]
can you try to set `verbose = True` for both the server and client in the config and make sure the data directories are empty when you run the above create command and if it doesn't work post both the oracle and the output of the client please?

**Comment by skurzhanskyi** [comment]
Of, course. Here all the outputs. The folder was empty before the start:
```
python3 oracle.py 
[client]
verbose = True
address = 127.0.0.1
port = 2355
datadir = ~/.sphinx/

[server]
verbose = True
address = 127.0.0.1
port = 2355
datadir = ~/.sphinx/
keydir = ~/.sphinx/

[websphinx]
pinentry = /usr/bin/pinentry
log = 

no server key found, generating...
please share `/Users/skurzhanskyi/.sphinx/server-key.pub` with all clients
Serving on ('127.0.0.1', 2355)
2018-11-23 01:01:06.594131 Connection from ('127.0.0.1', 50080)
Data received: b'T\x98\xf7\xed\xa3\x99\xcd\xb5\xb6\x9cY\xb0\x131\xc7 \xac\xf8\xee"b!U\xf7\xd6\xc2q=?QJ\xd4\xca\x0f\xd8\x8b\xb6\xfbG\x1a\x0c0\x0e\xd6\xe4\xeeQ&^\xfd:\xea8\xff\xa5\xf9\xff\x1a\xe1\xd5(\xdcg\t\x00\x9f\xa8\x03\xf4_\xe3\x1d\xa9\x8d=2i|\xdeKk\x13\x01K,u}\xbc\xe0\xd2l\xb0\x80\xcb\x1dS\x83\x8c\xe0\x7f\x1d\x88\xca\x90\x00C\x0f\x88\xf8\xe343)\xe9\x08\xff8\xa1\xd2W\xb3\x05\xff\x0e\x80 \xfeA\\\xf7\x99\x9f\x01x\xe9,\\\x1d\xedq\xb6\x1f\xe5[p\xe9v5\xfc?\xd2\xb6\xb15z&\x81\xe8J\x18A'
Send: b'\xea6R\x92\x91:\xbbs\t\xdd\xb4\xb7\xd6\xfb\xdf\x821\xb8r\xb2\xcbc\x94\r\xdb\xb95\x82\x10\xd1\x97l'
Close the client socket
```
```
echo 'my master password' | python3 ./sphinx.py create username https://example.com ulsd 0
Data sent: b'T\x98\xf7\xed\xa3\x99\xcd\xb5\xb6\x9cY\xb0\x131\xc7 \xac\xf8\xee"b!U\xf7\xd6\xc2q=?QJ\xd4\xca\x0f\xd8\x8b\xb6\xfbG\x1a\x0c0\x0e\xd6\xe4\xeeQ&^\xfd:\xea8\xff\xa5\xf9\xff\x1a\xe1\xd5(\xdcg\t\x00\x9f\xa8\x03\xf4_\xe3\x1d\xa9\x8d=2i|\xdeKk\x13\x01K,u}\xbc\xe0\xd2l\xb0\x80\xcb\x1dS\x83\x8c\xe0\x7f\x1d\x88\xca\x90\x00C\x0f\x88\xf8\xe343)\xe9\x08\xff8\xa1\xd2W\xb3\x05\xff\x0e\x80 \xfeA\\\xf7\x99\x9f\x01x\xe9,\\\x1d\xedq\xb6\x1f\xe5[p\xe9v5\xfc?\xd2\xb6\xb15z&\x81\xe8J\x18A'
Data received: b"b'[A\\xd7\\xf3\\xd9\\x9bW\\x8e,\\xaaU\\xc35\\xff\\xa4i\\x9a\\x95\\xbf\\xe7\\x98\\x8c`O\\xa2Z\\xb4\\xa4\\x08U.\\x03\\xb1.\\x18\\xcdL\\xe1\\xf4\\xc52M\\xcf\\x95\\xbdeQ\\xd3I\\xd4~w\\xcb6(M\\xbc\\x1e\\xae\\xef\\x82\\xf9\\xef\\x07\\xea6R\\x92\\x91:\\xbbs\\t\\xdd\\xb4\\xb7\\xd6\\xfb\\xdf\\x821\\xb8r\\xb2\\xcbc\\x94\\r\\xdb\\xb95\\x82\\x10\\xd1\\x97l'"
Fatal error: protocol.data_received() call failed.
protocol: <__main__.SphinxClientProtocol object at 0x10b89fd68>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 824, in _read_ready__data_received
    self._protocol.data_received(data)
  File "./sphinx.py", line 57, in data_received
    rwd=sphinxlib.finish(self.b, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pwdsphinx/sphinxlib.py", line 66, in finish
    __check(sphinxlib.sphinx_finish(bfac, resp, rwd))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pwdsphinx/sphinxlib.py", line 35, in __check
    raise ValueError
ValueError
The server closed the connection
Stop the event loop
```

**Comment by skurzhanskyi** [comment]
It's look like data recieved by client is different with the one that was sent by server.

**Comment by skurzhanskyi** [comment]
I also checked data send by oracle after signing and it looks like it is the same as sphinx received but like converted to bytes one more time.

**Comment by skurzhanskyi** [comment]
I checked all one more time and the data sent is exactly that is received (sent was just printed before signing). And the one that is sign open the same, as sent before signing.

**Comment by skurzhanskyi** [comment]
Also, I noticed that your master differs from what I installed by pip3 quite a lot. I'll try to clone your repository.

**Comment by skurzhanskyi** [comment]
After I clone repository everything started to work fine. As far as I understood, Pypi version is far older than the current one. Maybe it's better to change installation in README.

**Comment by stef** [comment]
thanks! i'll package up a new version for pypi.

**Comment by stef** [comment]
i just packaged v0.4 onto pypi. thanks for triggering this.

**Comment by skurzhanskyi** [comment]
Thank you for your responses.
Glad if I helped. :)
